config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    scope module: "v1" do
      resources :events, only: [:index]
      resources :links, only: [:index]
      resources :meetup_groups, only: [:index]
    end
  end

  match '(*any)', to: redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }, via: :all, constraints: RootDomainConstraint.new(:api, :www)

  root to: 'events#index'
  resources :events, except: [:destroy]
  resources :meetup_groups, except: [:edit, :update, :destroy]
  resources :urls, only: [:index, :show]
  resources :archived_urls, only: [:create]
  resources :cleaned_urls, only: [:create]
  resources :tweet_processing_jobs, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  get '/in', to: 'sessions#new', as: :in
  delete '/out', to: 'sessions#destroy', as: :out
  get 'auth/:provider/callback' => 'sessions#create'

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :verify_signed_in

  def index
    @unprocessed_tweet_count = Tweet.unprocessed.count
    if filter = params[:filter]
      @urls = ExtractedUrl.canonical.active.like(filter)
    else
      @urls = ExtractedUrl.canonical.active
    end
  end

  def show
    @url = ExtractedUrl.find(params[:id])
  end
end

app/views/urls/index.html.erb
<p><%= @unprocessed_tweet_count %> unprocessed Tweets <%= button_to 'Process', tweet_processing_jobs_path, class: 'pure-button pure-button-primary' %></p>
<p><%= @urls.count %> URLs for review.</p>
<table class="pure-table">
  <thead>
    <tr>
      <th>Archive</th>
      <th>Clean</th>
      <th>Source</th>
      <th>Link</th>
    </tr>
  </thead>
<% @urls.each do |url| %>
  <tr>
    <td><%= button_to 'Archive', archived_urls_path(id: url.id, filter: params[:filter]), class: 'pure-button' %></td>
    <td><%= button_to 'Clean', cleaned_urls_path(id: url.id, filter: params[:filter]), class: 'pure-button' %></td>
    <td>
      <% if url.source_type == 'Tweet' %>
        <%= link_to 'Tweet', url.source.original.url.to_s, class: 'pure-button pure-button-primary' %>
      <% else %>
        &nbsp;
      <% end %>
    </td>
    <td><%= link_to url.url, url.url, target: '_blank' %></td>
  </tr>
<% end %>
</table>

app/views/urls/show.html.erb
<p>
  <%= link_to @url.url, @url.url, target: '_blank' %>
</p>
<%= content_tag(:iframe, '', src: @url.url) %>
<p>
  <%= button_to 'Archive', archived_urls_path(id: @url.id, detail: true, filter: params[:filter]) %>

  <%= link_to 'Next', url_path(@url.next(params[:filter]), filter: params[:filter]) if @url.next(params[:filter]) %>
</p>