config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    scope module: "v1" do
      resources :events, only: [:index]
      resources :links, only: [:index]
      resources :meetup_groups, only: [:index]
    end
  end

  match '(*any)', to: redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }, via: :all, constraints: RootDomainConstraint.new(:api, :www)

  root to: 'events#index'
  resources :events, except: [:destroy]
  resources :meetup_groups, except: [:edit, :update, :destroy]
  resources :urls, only: [:index, :show]
  resources :archived_urls, only: [:create]
  resources :cleaned_urls, only: [:create]
  resources :tweet_processing_jobs, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  get '/in', to: 'sessions#new', as: :in
  delete '/out', to: 'sessions#destroy', as: :out
  get 'auth/:provider/callback' => 'sessions#create'

end

app/models/event.rb
class Event < ActiveRecord::Base

  with_options(on: :direct_input) do |di|
    di.validates_presence_of :title, :host, :city, :country, :description, :url
    di.validates :time_zone, inclusion: {
      in: ActiveSupport::TimeZone.all.map(&:name)
    }
  end

  def local_starts_at
    if utc_offset_fmt
      starts_at.getlocal(utc_offset_fmt)
    elsif time_zone
      starts_at.in_time_zone(time_zone)
    else
      starts_at
    end
  end

  scope :this_week, -> do
    now = Time.zone.now
    three_hours_ago = now - 3.hours
    eight_days_later = now + 8.days
    where(starts_at: three_hours_ago..eight_days_later)
  end

  scope :this_month, -> do
    now = Time.zone.now
    three_hours_ago = now - 3.hours
    thirty_days_later = now + 30.days
    where(starts_at: three_hours_ago..thirty_days_later)
  end

  scope :last_week, -> do
    now = Time.zone.now
    eight_days_ago = now - 8.days
    where(starts_at: eight_days_ago..now)
  end

  scope :last_month, -> do
    now = Time.zone.now
    thirty_days_ago = now + 30.days
    where(starts_at: thirty_days_ago..now)
  end

  scope :upcoming, -> do
    now = Time.zone.now
    three_hours_ago = now - 3.hours

    where('starts_at > ?', three_hours_ago)
  end

  scope :occurred, -> do
    where('starts_at < ?', Time.zone.now)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :verify_signed_in, except: [:index]

  def index
    @events = Event.upcoming.order(starts_at: :asc)
  end

  def new
    @event = Event.new
  end

  def create
    if params[:link_only]
      @event = MeetupScraper.new.scrape_from_meetup_url(params[:event][:url])
      redirect_to event_path(@event)
    else
      @event = Event.new(event_params_processed_for_time_zone)
      if @event.save(context: :direct_input)
        redirect_to event_path(@event), notice: "Success"
      else
        render :new
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
    # Rails will present time as UTC when we want time as if in timezone
    @event.starts_at = Time.zone.local_to_utc(@event.local_starts_at)
  end

  def update
    @event = Event.find(params[:id])
    @event.attributes = event_params_processed_for_time_zone
    if @event.save(context: :direct_input)
      redirect_to event_path(@event), notice: "Success"
    else
      render :edit
    end
  end

  private

  def event_params_processed_for_time_zone
    TimeZoneParamsProcessor.process(event_params)
  end

  def event_params
    attrs = [
      :title,
      :starts_at,
      :time_zone,
      :host,
      :city,
      :country,
      :description,
      :url
    ]
    params.require(:event).permit(*attrs)
  end
end

app/controllers/v1/events_controller.rb
class V1::EventsController < ApplicationController
  def index
    @events = Event.upcoming.order(starts_at: :asc)
    render json: @events
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def date_and_time_display(time)
    time.to_formatted_s(:date_and_time)
  end
end

app/views/events/_event.html.erb
<!--<span class="fa-stack fa-3x">
  <i class="fa fa-calendar-o fa-stack-2x"></i>
  <strong class="fa-stack-1x calendar-text">27</strong>
</span>-->

<div class="meetup-group-detail">
  <h2 class="content-subhead"><%= event.title %></h2>
  <h3><%= date_and_time_display(event.local_starts_at) %></h3>
  <h4>
  <%= event.city %>, <%= event.country %> (<%= sanitize event.host %>)<br>
  </h4>
  <%= sanitize event.description %><br>
  <%= link_to "View on Meetup.com", event.url, class: 'pure-button pure-button-primary' %>
<% if current_identity -%>
  | <%= link_to "Show", event_path(event) %>
  | <%= link_to "Edit", edit_event_path(event) %>
<% end -%>
  </p>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event, html: { class: 'pure-form pure-form-aligned' } do |f| %>
  <fieldset>
    <legend>Event details</legend>

    <div class="pure-control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="pure-control-group">
      <%= f.label :starts_at %>
      <%= f.datetime_select :starts_at %>
    </div>

    <div class="pure-control-group">
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, nil, default: "UTC" %>
    </div>

    <div class="pure-control-group">
      <%= f.label :host %>
      <%= f.text_field :host %>
    </div>

    <div class="pure-control-group">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="pure-control-group">
      <%= f.label :country %>
      <%= f.country_select :country %>
    </div>

    <div class="pure-control-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="pure-control-group">
      <%= f.label :url, "Link to Details" %>
      <%= f.text_field :url %>
    </div>

    <div class="pure-controls">
      <%= f.submit "Update", class: 'pure-button pure-button-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/events/index.html.erb
<h1>Elm Events</h1>
<%= render @events %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event, html: { class: 'pure-form pure-form-aligned' } do |f| %>
  <fieldset>
    <legend>A. Paste in the URL of a Meetup Event OR</legend>
    <div class="pure-control-group">
      <%= f.label :url, "Meetup Event URL" %>
      <%= f.text_field :url %>
    </div>
    <%= hidden_field_tag :link_only, true %>
    <div class="pure-controls">
      <%= f.submit "Create", class: 'pure-button pure-button-primary' %>
    </div>
  </fieldset>
<% end %>

<br>

<%= form_for @event, html: { class: 'pure-form pure-form-aligned' } do |f| %>
  <fieldset>
    <legend>B. Enter Event details by hand</legend>

    <div class="pure-control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="pure-control-group">
      <%= f.label :starts_at %>
      <%= f.datetime_select :starts_at %>
    </div>

    <div class="pure-control-group">
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, nil, default: "UTC" %>
    </div>

    <div class="pure-control-group">
      <%= f.label :host %>
      <%= f.text_field :host %>
    </div>

    <div class="pure-control-group">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="pure-control-group">
      <%= f.label :country %>
      <%= f.country_select :country %>
    </div>

    <div class="pure-control-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="pure-control-group">
      <%= f.label :url, "Link to Details" %>
      <%= f.text_field :url %>
    </div>

    <div class="pure-controls">
      <%= f.submit "Create", class: 'pure-button pure-button-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/events/show.html.erb
<%= link_to "Edit", edit_event_path(@event) %>

<table class="pure-table pure-table-bordered">
  <tr>
    <td>Title</td>
    <td><%= @event.title %></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%= sanitize @event.description %></td>
  </tr>
  <tr>
    <td>Country</td>
    <td><%= @event.country %></td>
  </tr>
  <tr>
    <td>City</td>
    <td><%= @event.city %></td>
  </tr>
  <tr>
    <td>Host</td>
    <td><%= sanitize @event.host %></td>
  </tr>
  <tr>
    <td>URL</td>
    <td><%= @event.url %></td>
  </tr>
  <tr>
    <td>External ID</td>
    <td><%= @event.external_id %></td>
  </tr>
  <tr>
    <td>External Updated At</td>
    <td><%= @event.external_updated_at %></td>
  </tr>
  <tr>
    <td>Starts At</td>
    <td><%= @event.starts_at %></td>
  </tr>
  <tr>
    <td>Time Zone</td>
    <td><%= @event.time_zone %></td>
  </tr>
  <tr>
    <td>Local Starts At</td>
    <td><%= @event.local_starts_at %></td>
  </tr>
  <tr>
    <td>Local Starts At (formatted)</td>
    <td><%= date_and_time_display(@event.local_starts_at) %></td>
  </tr>
  <tr>
    <td>UTC Offset (formatted)</td>
    <td><%= @event.utc_offset_fmt %></td>
  </tr>
  <tr>
    <td>UTC Offset</td>
    <td><%= @event.utc_offset %></td>
  </tr>
  <tr>
    <td>Created At</td>
    <td><%= @event.created_at %></td>
  </tr>
  <tr>
    <td>Updated At</td>
    <td><%= @event.updated_at %></td>
  </tr>
</table>