config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    scope module: "v1" do
      resources :events, only: [:index]
      resources :links, only: [:index]
      resources :meetup_groups, only: [:index]
    end
  end

  match '(*any)', to: redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }, via: :all, constraints: RootDomainConstraint.new(:api, :www)

  root to: 'events#index'
  resources :events, except: [:destroy]
  resources :meetup_groups, except: [:edit, :update, :destroy]
  resources :urls, only: [:index, :show]
  resources :archived_urls, only: [:create]
  resources :cleaned_urls, only: [:create]
  resources :tweet_processing_jobs, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  get '/in', to: 'sessions#new', as: :in
  delete '/out', to: 'sessions#destroy', as: :out
  get 'auth/:provider/callback' => 'sessions#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Elm Log</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="layout">
      <!-- Menu toggle -->
      <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
      </a>

      <div id="menu">
        <div class="pure-menu">
          <p class="pure-menu-heading" style="padding-left: 0.6em;">Community</p>
          <ul class="pure-menu-list">
            <li class="pure-menu-item"><%= link_to("Events", root_path, class: 'pure-menu-link') %></li>
          </ul>
          <ul class="pure-menu-list">
            <li class="pure-menu-item"><%= link_to("Meetups", meetup_groups_path, class: 'pure-menu-link') %></li>
          </ul>

          <ul class="pure-menu-list" style="padding-top: 15px;">
            <% if current_identity %>
              <li class="pure-menu-item" style="text-align: center; margin: 5px; display: block;">
                <%= link_to(new_meetup_group_path, class: 'pure-button pure-button-primary', style: 'display: block; text-align: left;') do %>
                  <i class="fa fa-users"></i> New Meetup
                <% end %>
              </li>
              <li class="pure-menu-item" style="text-align: center; margin: 5px;">
                <%= link_to(new_event_path, class: 'pure-button pure-button-primary', style: 'display: block; text-align: left;') do %>
                  <i class="fa fa-calendar-plus-o"></i> New Event
                <% end %>
              </li>
            <% end %>
          </ul>
          <ul class="pure-menu-list" style="margin-top: 15px;padding-top:15px">
              <% if current_identity %>
                <li class="pure-menu-item" style="text-align: center; margin: 5px;">
                  <strong><%= current_identity.name %></strong>
                </li>
                <li class="pure-menu-item" style="text-align: center; margin: 15px;">
                  <%= button_to "Sign Out", out_path, method: :delete, class: 'pure-button' %>
                </li>
              <% else %>
                <li class="pure-menu-item" style="text-align: center; margin: 5px;">
                  <%= button_to in_path, method: :get, class: 'pure-button' do %>
                    <i class="fa fa-github"></i> Sign In
                  <% end %>
                </li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <div id="main">
        <div class="header">
          <h1>Elm Log</h1>
        </div>

        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>